// MinIO Rust Library for Amazon S3 Compatible Cloud Storage
// Copyright 2025 MinIO, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use crate::s3::MinioClient;
use crate::s3::builders::{BucketCommon, BucketCommonBuilder};
use crate::s3::error::ValidationErr;
use crate::s3::response::DeleteBucketNotificationResponse;
use crate::s3::segmented_bytes::SegmentedBytes;
use crate::s3::types::{NotificationConfig, S3Api, S3Request, ToS3Request};
use crate::s3::utils::{check_bucket_name, insert};
use bytes::Bytes;
use http::Method;
use std::sync::Arc;

/// Argument builder for the [`DeleteBucketNotification`](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketNotificationConfiguration.html) S3 API operation.
/// Note: on Amazon S3, a bucket notification is deleted by setting its configuration to empty.
///
/// This struct constructs the parameters required for the [`Client::delete_bucket_notification`](crate::s3::client::MinioClient::delete_bucket_notification) method.
/// See [Amazon S3: Managing Bucket Notifications](https://docs.aws.amazon.com/AmazonS3/latest/userguide/NotificationHowTo.html) for more information.
pub type DeleteBucketNotification = BucketCommon<DeleteBucketNotificationPhantomData>;

#[doc(hidden)]
#[derive(Clone, Debug)]
pub struct DeleteBucketNotificationPhantomData;

impl S3Api for DeleteBucketNotification {
    type S3Response = DeleteBucketNotificationResponse;
}

/// Builder type for [`DeleteBucketNotification`] that is returned by [`MinioClient::delete_bucket_notification`](crate::s3::client::MinioClient::delete_bucket_notification).
///
/// This type alias simplifies the complex generic signature generated by the `typed_builder` crate.
pub type DeleteBucketNotificationBldr = BucketCommonBuilder<
    DeleteBucketNotificationPhantomData,
    ((MinioClient,), (), (), (), (String,), ()),
>;

impl ToS3Request for DeleteBucketNotification {
    fn to_s3request(self) -> Result<S3Request, ValidationErr> {
        check_bucket_name(&self.bucket, true)?;

        const CONFIG: NotificationConfig = NotificationConfig {
            cloud_func_config_list: None,
            queue_config_list: None,
            topic_config_list: None,
        };
        let bytes: Bytes = CONFIG.to_xml().into();
        let body: Arc<SegmentedBytes> = Arc::new(SegmentedBytes::from(bytes));
        //TODO consider const body

        Ok(S3Request::builder()
            .client(self.client)
            .method(Method::PUT)
            .region(self.region)
            .bucket(self.bucket)
            .query_params(insert(self.extra_query_params, "notification"))
            .headers(self.extra_headers.unwrap_or_default())
            .body(body)
            .build())
    }
}
