// MinIO Rust Library for Amazon S3 Compatible Cloud Storage
// Copyright 2025 MinIO, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use crate::s3::bucket_policy_config::BucketPolicyConfig;
use crate::s3::client::MinioClient;
use crate::s3::error::ValidationErr;
use crate::s3::multimap_ext::Multimap;
use crate::s3::response::PutBucketPolicyResponse;
use crate::s3::segmented_bytes::SegmentedBytes;
use crate::s3::types::{BucketName, Region, S3Api, S3Request, ToS3Request};
use crate::s3::utils::insert;
use bytes::Bytes;
use http::Method;
use std::sync::Arc;
use typed_builder::TypedBuilder;

/// Argument builder for the [`PutBucketPolicy`](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketPolicy.html) S3 API operation.
///
/// This struct constructs the parameters required for the [`Client::put_bucket_policy`](crate::s3::client::MinioClient::put_bucket_policy) method.
#[derive(Clone, Debug, TypedBuilder)]
pub struct PutBucketPolicy {
    #[builder(!default)] // force required
    client: MinioClient,
    #[builder(default, setter(into))]
    extra_headers: Option<Multimap>,
    #[builder(default, setter(into))]
    extra_query_params: Option<Multimap>,
    #[builder(default, setter(into))]
    region: Option<Region>,
    #[builder(setter(into), !default)]
    bucket: BucketName,
    #[builder(default, setter(transform = |c: impl TryInto<BucketPolicyConfig, Error = impl Into<crate::s3::error::ValidationErr>>| c.try_into().map_err(Into::into).unwrap()))]
    config: BucketPolicyConfig,
}

/// Builder type for [`PutBucketPolicy`] that is returned by [`MinioClient::put_bucket_policy`](crate::s3::client::MinioClient::put_bucket_policy).
///
/// This type alias simplifies the complex generic signature generated by the `typed_builder` crate.
pub type PutBucketPolicyBldr =
    PutBucketPolicyBuilder<((MinioClient,), (), (), (), (BucketName,), ())>;

impl S3Api for PutBucketPolicy {
    type S3Response = PutBucketPolicyResponse;
}

impl ToS3Request for PutBucketPolicy {
    fn to_s3request(self) -> Result<S3Request, ValidationErr> {
        let json_str = self.config.to_json().map_err(|e| match e {
            crate::s3::error::Error::Validation(v) => v,
            _ => ValidationErr::xml_error("Failed to serialize policy to JSON"),
        })?;
        let bytes: Bytes = json_str.into();
        let body = Arc::new(SegmentedBytes::from(bytes));

        Ok(S3Request::builder()
            .client(self.client)
            .method(Method::PUT)
            .region(self.region)
            .bucket(self.bucket)
            .query_params(insert(self.extra_query_params, "policy"))
            .headers(self.extra_headers.unwrap_or_default())
            .body(body)
            .build())
    }
}
