// MinIO Rust Library for Amazon S3 Compatible Cloud Storage
// Copyright 2025 MinIO, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use crate::s3::client::MinioClient;
use crate::s3::error::ValidationErr;
use crate::s3::multimap_ext::{Multimap, MultimapExt};
use crate::s3::response::PutObjectTaggingResponse;
use crate::s3::segmented_bytes::SegmentedBytes;
use crate::s3::types::{BucketName, ObjectKey, Region, S3Api, S3Request, ToS3Request, VersionId};
use crate::s3::utils::insert;
use bytes::Bytes;
use http::Method;
use std::collections::HashMap;
use std::sync::Arc;
use typed_builder::TypedBuilder;

/// Argument builder for the [`PutObjectTagging`](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObjectTagging.html) S3 API operation.
///
/// This struct constructs the parameters required for the [`Client::put_object_tagging`](crate::s3::client::MinioClient::put_object_tagging) method.
#[derive(Clone, Debug, TypedBuilder)]
pub struct PutObjectTagging {
    #[builder(!default)] // force required
    client: MinioClient,
    #[builder(default, setter(into))]
    extra_headers: Option<Multimap>,
    #[builder(default, setter(into))]
    extra_query_params: Option<Multimap>,
    #[builder(default, setter(into))]
    region: Option<Region>,
    #[builder(setter(into))] // force required + accept Into<String>
    #[builder(!default)]
    bucket: BucketName,
    #[builder(setter(into))] // force required + accept Into<String>
    #[builder(!default)]
    object: ObjectKey,
    #[builder(default, setter(into))]
    version_id: Option<VersionId>,
    #[builder(default)]
    tags: HashMap<String, String>,
}

/// Builder type for [`PutObjectTagging`] that is returned by [`MinioClient::put_object_tagging`](crate::s3::client::MinioClient::put_object_tagging).
///
/// This type alias simplifies the complex generic signature generated by the `typed_builder` crate.
pub type PutObjectTaggingBldr = PutObjectTaggingBuilder<(
    (MinioClient,),
    (),
    (),
    (),
    (BucketName,),
    (ObjectKey,),
    (),
    (),
)>;

impl S3Api for PutObjectTagging {
    type S3Response = PutObjectTaggingResponse;
}

impl ToS3Request for PutObjectTagging {
    fn to_s3request(self) -> Result<S3Request, ValidationErr> {
        let mut query_params: Multimap = insert(self.extra_query_params, "tagging");
        query_params.add_version(self.version_id);

        let data: String = {
            let mut data = String::from("<Tagging>");
            if !self.tags.is_empty() {
                data.push_str("<TagSet>");
                for (key, value) in self.tags.iter() {
                    data.push_str("<Tag>");
                    data.push_str("<Key>");
                    data.push_str(key);
                    data.push_str("</Key>");
                    data.push_str("<Value>");
                    data.push_str(value);
                    data.push_str("</Value>");
                    data.push_str("</Tag>");
                }
                data.push_str("</TagSet>");
            }
            data.push_str("</Tagging>");
            data
        };
        let body = Arc::new(SegmentedBytes::from(Bytes::from(data)));

        Ok(S3Request::builder()
            .client(self.client)
            .method(Method::PUT)
            .region(self.region)
            .bucket(self.bucket)
            .query_params(query_params)
            .object(self.object)
            .headers(self.extra_headers.unwrap_or_default())
            .body(body)
            .build())
    }
}
