// MinIO Rust Library for Amazon S3 Compatible Cloud Storage
// Copyright 2025 MinIO, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use crate::s3::client::MinioClient;
use crate::s3::error::ValidationErr;
use crate::s3::header_constants::*;
use crate::s3::multimap_ext::{Multimap, MultimapExt};
use crate::s3::response::PutObjectRetentionResponse;
use crate::s3::segmented_bytes::SegmentedBytes;
use crate::s3::types::{
    BucketName, ObjectKey, Region, RetentionMode, S3Api, S3Request, ToS3Request, VersionId,
};
use crate::s3::utils::{UtcTime, insert, md5sum_hash, to_iso8601utc};
use bytes::Bytes;
use http::Method;
use std::sync::Arc;
use typed_builder::TypedBuilder;

/// Argument builder for the [`PutObjectRetention`](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObjectRetention.html) S3 API operation.
///
/// This struct constructs the parameters required for the [`Client::put_object_retention`](crate::s3::client::MinioClient::put_object_retention) method.
#[derive(Clone, Debug, TypedBuilder)]
pub struct PutObjectRetention {
    #[builder(!default)] // force required
    client: MinioClient,
    #[builder(default, setter(into))]
    extra_headers: Option<Multimap>,
    #[builder(default, setter(into))]
    extra_query_params: Option<Multimap>,
    #[builder(default, setter(into))]
    region: Option<Region>,
    #[builder(setter(into))] // force required + accept Into<String>
    #[builder(!default)]
    bucket: BucketName,
    #[builder(setter(into))] // force required + accept Into<String>
    #[builder(!default)]
    object: ObjectKey,
    #[builder(default, setter(into))]
    version_id: Option<VersionId>,
    #[builder(default = false)]
    bypass_governance_mode: bool,
    #[builder(default, setter(into))]
    retention_mode: Option<RetentionMode>,
    #[builder(default, setter(into))]
    retain_until_date: Option<UtcTime>,
}

/// Builder type for [`PutObjectRetention`] that is returned by [`MinioClient::put_object_retention`](crate::s3::client::MinioClient::put_object_retention).
///
/// This type alias simplifies the complex generic signature generated by the `typed_builder` crate.
pub type PutObjectRetentionBldr = PutObjectRetentionBuilder<(
    (MinioClient,),
    (),
    (),
    (),
    (BucketName,),
    (ObjectKey,),
    (),
    (),
    (),
    (),
)>;

impl S3Api for PutObjectRetention {
    type S3Response = PutObjectRetentionResponse;
}

impl ToS3Request for PutObjectRetention {
    fn to_s3request(self) -> Result<S3Request, ValidationErr> {
        {
            if self.retention_mode.is_some() ^ self.retain_until_date.is_some() {
                return Err(ValidationErr::InvalidRetentionConfig(
                    "both mode and retain_until_date must be set or unset".into(),
                ));
            }
        }

        let bytes: Bytes = {
            let mut data: String = "<Retention>".into();
            if let Some(v) = &self.retention_mode {
                data.push_str("<Mode>");
                data.push_str(&v.to_string());
                data.push_str("</Mode>");
            }
            if let Some(v) = &self.retain_until_date {
                data.push_str("<RetainUntilDate>");
                data.push_str(&to_iso8601utc(*v));
                data.push_str("</RetainUntilDate>");
            }
            data.push_str("</Retention>");
            Bytes::from(data)
        };

        let mut headers: Multimap = self.extra_headers.unwrap_or_default();
        if self.bypass_governance_mode {
            headers.add(X_AMZ_BYPASS_GOVERNANCE_RETENTION, "true");
        }
        headers.add(CONTENT_MD5, md5sum_hash(bytes.as_ref()));

        let mut query_params: Multimap = insert(self.extra_query_params, "retention");
        query_params.add_version(self.version_id);

        let body = Arc::new(SegmentedBytes::from(bytes));

        Ok(S3Request::builder()
            .client(self.client)
            .method(Method::PUT)
            .region(self.region)
            .bucket(self.bucket)
            .query_params(query_params)
            .headers(headers)
            .object(self.object)
            .body(body)
            .build())
    }
}
