// MinIO Rust Library for Amazon S3 Compatible Cloud Storage
// Copyright 2025 MinIO, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use crate::s3::client::MinioClient;
use crate::s3::error::ValidationErr;
use crate::s3::header_constants::*;
use crate::s3::multimap_ext::{Multimap, MultimapExt};
use crate::s3::response::PutObjectLegalHoldResponse;
use crate::s3::segmented_bytes::SegmentedBytes;
use crate::s3::types::{S3Api, S3Request, ToS3Request};
use crate::s3::utils::{check_bucket_name, check_object_name, insert, md5sum_hash};
use bytes::Bytes;
use http::Method;
use std::sync::Arc;
use typed_builder::TypedBuilder;

/// Argument builder for the [`PutObjectLegalHold`](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObjectLegalHold.html) S3 API operation.
///
/// This struct constructs the parameters required for the [`Client::put_object_legal_hold`](crate::s3::client::MinioClient::put_object_legal_hold) method.
#[derive(Clone, Debug, TypedBuilder)]
pub struct PutObjectLegalHold {
    #[builder(!default)] // force required
    client: MinioClient,
    #[builder(default, setter(into))]
    extra_headers: Option<Multimap>,
    #[builder(default, setter(into))]
    extra_query_params: Option<Multimap>,
    #[builder(default, setter(into))]
    region: Option<String>,
    #[builder(setter(into))] // force required + accept Into<String>
    bucket: String,
    #[builder(setter(into))] // force required + accept Into<String>
    object: String,
    #[builder(default, setter(into))]
    version_id: Option<String>,
    #[builder(default, setter(into))]
    legal_hold: Option<bool>,
}

/// Builder type for [`PutObjectLegalHold`] that is returned by [`MinioClient::put_object_legal_hold`](crate::s3::client::MinioClient::put_object_legal_hold).
///
/// This type alias simplifies the complex generic signature generated by the `typed_builder` crate.
pub type PutObjectLegalHoldBldr = PutObjectLegalHoldBuilder<(
    (MinioClient,),
    (),
    (),
    (),
    (String,),
    (String,),
    (),
    (Option<bool>,),
)>;

impl S3Api for PutObjectLegalHold {
    type S3Response = PutObjectLegalHoldResponse;
}

impl ToS3Request for PutObjectLegalHold {
    fn to_s3request(self) -> Result<S3Request, ValidationErr> {
        check_bucket_name(&self.bucket, true)?;
        check_object_name(&self.object)?;

        let mut headers: Multimap = self.extra_headers.unwrap_or_default();
        let mut query_params: Multimap = insert(self.extra_query_params, "legal-hold");
        query_params.add_version(self.version_id);

        let payload: &str = match self.legal_hold {
            Some(true) => "<LegalHold><Status>ON</Status></LegalHold>",
            _ => "<LegalHold><Status>OFF</Status></LegalHold>",
        };
        let bytes: Bytes = Bytes::from(payload);
        // TODO consider const payload with precalculated md5

        headers.add(CONTENT_MD5, md5sum_hash(bytes.as_ref()));
        let body = Arc::new(SegmentedBytes::from(bytes));

        Ok(S3Request::builder()
            .client(self.client)
            .method(Method::PUT)
            .region(self.region)
            .bucket(self.bucket)
            .query_params(query_params)
            .headers(headers)
            .object(self.object)
            .body(body)
            .build())
    }
}
