// MinIO Rust Library for Amazon S3 Compatible Cloud Storage
// Copyright 2025 MinIO, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use crate::s3::client::MinioClient;
use crate::s3::error::ValidationErr;
use crate::s3::header_constants::*;
use crate::s3::multimap_ext::{Multimap, MultimapExt};
use crate::s3::response::RenameObjectResponse;
use crate::s3::types::{BucketName, ObjectKey, Region, S3Api, S3Request, ToS3Request};
use crate::s3::utils::urlencode_object_key;
use http::Method;
use typed_builder::TypedBuilder;

const SLASH: &str = "/";

/// Argument builder for the `RenameObject` operation (MinIO extension).
///
/// Renames an object within a single bucket in one server-side request. The
/// server distinguishes this from `CopyObject`/`PutObject` purely by the
/// presence of the `x-amz-rename-source` header. Renames are only supported on
/// unversioned buckets.
///
/// See: <https://min.io/docs/minio/linux/developers/minio-drivers.html>
///
/// This struct constructs the parameters required for the
/// [`Client::rename_object`](crate::s3::client::MinioClient::rename_object) method.
#[derive(Debug, Clone, TypedBuilder)]
pub struct RenameObject {
    #[builder(!default)] // force required
    client: MinioClient,
    #[builder(default, setter(into))]
    extra_headers: Option<Multimap>,
    #[builder(default, setter(into))]
    extra_query_params: Option<Multimap>,
    #[builder(default, setter(into))]
    region: Option<Region>,
    #[builder(setter(into), !default)]
    bucket: BucketName,
    #[builder(setter(into), !default)]
    src_object: ObjectKey,
    #[builder(setter(into), !default)]
    dst_object: ObjectKey,
    /// `x-amz-rename-source-if-match`. A literal `"*"` is sent unquoted, a
    /// concrete ETag is sent quoted.
    #[builder(default, setter(into))]
    src_match_etag: Option<String>,
    /// `x-amz-rename-source-if-none-match`. A literal `"*"` is sent unquoted, a
    /// concrete ETag is sent quoted.
    #[builder(default, setter(into))]
    src_not_match_etag: Option<String>,
    /// `x-amz-rename-source-if-modified-since` (HTTP-date), sent verbatim.
    #[builder(default, setter(into))]
    src_modified_since: Option<String>,
    /// `x-amz-rename-source-if-unmodified-since` (HTTP-date), sent verbatim.
    #[builder(default, setter(into))]
    src_unmodified_since: Option<String>,
    /// `If-Match` on the destination. A literal `"*"` is sent unquoted, a
    /// concrete ETag is sent quoted.
    #[builder(default, setter(into))]
    dst_match_etag: Option<String>,
    /// `If-None-Match` on the destination. A literal `"*"` is sent unquoted, a
    /// concrete ETag is sent quoted.
    #[builder(default, setter(into))]
    dst_not_match_etag: Option<String>,
    /// `If-Modified-Since` on the destination (HTTP-date), sent verbatim.
    #[builder(default, setter(into))]
    dst_modified_since: Option<String>,
    /// `If-Unmodified-Since` on the destination (HTTP-date), sent verbatim.
    #[builder(default, setter(into))]
    dst_unmodified_since: Option<String>,
}

/// Builder type for [`RenameObject`] that is returned by [`MinioClient::rename_object`](crate::s3::client::MinioClient::rename_object).
///
/// This type alias simplifies the complex generic signature generated by the `typed_builder` crate.
pub type RenameObjectBldr = RenameObjectBuilder<(
    (MinioClient,),
    (),
    (),
    (),
    (BucketName,),
    (ObjectKey,),
    (ObjectKey,),
    (),
    (),
    (),
    (),
    (),
    (),
    (),
    (),
)>;

impl S3Api for RenameObject {
    type S3Response = RenameObjectResponse;
}

fn conditional_etag_value(etag: &str) -> String {
    if etag == "*" {
        etag.to_string()
    } else {
        format!("\"{etag}\"")
    }
}

/// Builds the `x-amz-rename-source` header value as `/{bucket}/{object}`, percent-encoding
/// the object key (preserving `/`) the same way minio-go encodes `x-amz-copy-source`.
/// The server decodes it via `url.Parse().Path`, so the key must be encoded here.
fn rename_source_value(bucket: &str, src_object: &str) -> String {
    let encoded = urlencode_object_key(src_object);
    let mut value = String::with_capacity(bucket.len() + encoded.len() + 2);
    value.push('/');
    value.push_str(bucket);
    value.push('/');
    value.push_str(&encoded);
    value
}

fn validate_rename(src_object: &str, dst_object: &str) -> Result<(), ValidationErr> {
    let src_is_dir = src_object.ends_with(SLASH);
    let dst_is_dir = dst_object.ends_with(SLASH);
    if src_is_dir != dst_is_dir {
        return Err(ValidationErr::InvalidObjectName(format!(
            "rename directory-suffix mismatch: source '{src_object}' and destination '{dst_object}' must both be directories or both be objects"
        )));
    }

    let src_prefix = if src_is_dir {
        src_object.to_string()
    } else {
        format!("{src_object}{SLASH}")
    };
    let dst_prefix = if dst_is_dir {
        dst_object.to_string()
    } else {
        format!("{dst_object}{SLASH}")
    };
    if dst_object.starts_with(&src_prefix) || src_object.starts_with(&dst_prefix) {
        return Err(ValidationErr::InvalidObjectName(format!(
            "rename prefix nesting: source '{src_object}' and destination '{dst_object}' may not be nested under one another"
        )));
    }

    Ok(())
}

impl ToS3Request for RenameObject {
    fn to_s3request(self) -> Result<S3Request, ValidationErr> {
        validate_rename(self.src_object.as_str(), self.dst_object.as_str())?;

        let mut headers: Multimap = self.extra_headers.unwrap_or_default();

        headers.add(
            X_AMZ_RENAME_SOURCE,
            rename_source_value(self.bucket.as_str(), self.src_object.as_str()),
        );

        if let Some(etag) = &self.src_match_etag {
            headers.add(X_AMZ_RENAME_SOURCE_IF_MATCH, conditional_etag_value(etag));
        }
        if let Some(etag) = &self.src_not_match_etag {
            headers.add(
                X_AMZ_RENAME_SOURCE_IF_NONE_MATCH,
                conditional_etag_value(etag),
            );
        }
        if let Some(v) = self.src_modified_since {
            headers.add(X_AMZ_RENAME_SOURCE_IF_MODIFIED_SINCE, v);
        }
        if let Some(v) = self.src_unmodified_since {
            headers.add(X_AMZ_RENAME_SOURCE_IF_UNMODIFIED_SINCE, v);
        }

        if let Some(etag) = &self.dst_match_etag {
            headers.add(IF_MATCH, conditional_etag_value(etag));
        }
        if let Some(etag) = &self.dst_not_match_etag {
            headers.add(IF_NONE_MATCH, conditional_etag_value(etag));
        }
        if let Some(v) = self.dst_modified_since {
            headers.add(IF_MODIFIED_SINCE, v);
        }
        if let Some(v) = self.dst_unmodified_since {
            headers.add(IF_UNMODIFIED_SINCE, v);
        }

        Ok(S3Request::builder()
            .client(self.client)
            .method(Method::PUT)
            .region(self.region)
            .bucket(self.bucket)
            .object(self.dst_object)
            .query_params(self.extra_query_params.unwrap_or_default())
            .headers(headers)
            .expect_200_ok_with_error(true)
            .build())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rename_source_value_format() {
        assert_eq!(
            rename_source_value("my-bucket", "src/object.txt"),
            "/my-bucket/src/object.txt"
        );
    }

    #[test]
    fn rename_source_value_url_encodes_object() {
        assert_eq!(
            rename_source_value("my-bucket", "a b+c?d"),
            "/my-bucket/a%20b%2Bc%3Fd"
        );
    }

    #[test]
    fn conditional_etag_wildcard_is_unquoted() {
        assert_eq!(conditional_etag_value("*"), "*");
    }

    #[test]
    fn conditional_etag_concrete_is_quoted() {
        assert_eq!(conditional_etag_value("abc123"), "\"abc123\"");
    }

    #[test]
    fn validate_rename_object_to_object_ok() {
        assert!(validate_rename("foo", "bar").is_ok());
        assert!(validate_rename("a/b", "a/c").is_ok());
    }

    #[test]
    fn validate_rename_dir_to_dir_ok() {
        assert!(validate_rename("dir/", "other/").is_ok());
    }

    #[test]
    fn validate_rename_dir_parity_mismatch_rejected() {
        assert!(matches!(
            validate_rename("dir/", "obj"),
            Err(ValidationErr::InvalidObjectName(_))
        ));
        assert!(matches!(
            validate_rename("obj", "dir/"),
            Err(ValidationErr::InvalidObjectName(_))
        ));
    }

    #[test]
    fn validate_rename_dst_nested_under_src_rejected() {
        assert!(matches!(
            validate_rename("a/b", "a/b/c"),
            Err(ValidationErr::InvalidObjectName(_))
        ));
    }

    #[test]
    fn validate_rename_src_nested_under_dst_rejected() {
        assert!(matches!(
            validate_rename("a/b/c", "a/b"),
            Err(ValidationErr::InvalidObjectName(_))
        ));
    }

    #[test]
    fn validate_rename_dir_nested_rejected() {
        assert!(matches!(
            validate_rename("dir/", "dir/sub/"),
            Err(ValidationErr::InvalidObjectName(_))
        ));
    }

    #[test]
    fn validate_rename_sibling_prefix_not_nested() {
        assert!(validate_rename("ab", "abc").is_ok());
        assert!(validate_rename("a/b", "a/bc").is_ok());
    }
}
