// MinIO Rust Library for Amazon S3 Compatible Cloud Storage
// Copyright 2025 MinIO, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use crate::s3::client::MinioClient;
use crate::s3::error::ValidationErr;
use crate::s3::header_constants::CONTENT_MD5;
use crate::s3::multimap_ext::{Multimap, MultimapExt};
use crate::s3::response::UpdateObjectEncryptionResponse;
use crate::s3::segmented_bytes::SegmentedBytes;
use crate::s3::types::{BucketName, ObjectKey, Region, S3Api, S3Request, ToS3Request, VersionId};
use crate::s3::utils::{insert, md5sum_hash};
use bytes::Bytes;
use http::Method;
use std::sync::Arc;
use typed_builder::TypedBuilder;

/// Argument builder for the `UpdateObjectEncryption` operation (MinIO extension).
///
/// This is a MinIO-specific extension that rotates the SSE-KMS encryption key envelope of an
/// existing object in-place, without re-reading or re-writing the object data. The object must
/// already be encrypted with SSE-S3 or SSE-KMS; SSE-C objects are not supported.
/// See: <https://min.io/docs/minio/linux/developers/minio-drivers.html>
///
/// This struct constructs the parameters required for the [`Client::update_object_encryption`](crate::s3::client::MinioClient::update_object_encryption) method.
#[derive(Clone, Debug, TypedBuilder)]
pub struct UpdateObjectEncryption {
    #[builder(!default)] // force required
    client: MinioClient,
    #[builder(default, setter(into))]
    extra_headers: Option<Multimap>,
    #[builder(default, setter(into))]
    extra_query_params: Option<Multimap>,
    #[builder(default, setter(into))]
    region: Option<Region>,
    #[builder(setter(into), !default)]
    bucket: BucketName,
    #[builder(setter(into), !default)]
    object: ObjectKey,
    #[builder(setter(into))] // force required + accept Into<String>
    kms_key_arn: String,
    #[builder(default, setter(into))]
    bucket_key_enabled: Option<bool>,
    #[builder(default, setter(into))]
    version_id: Option<VersionId>,
}

/// Builder type for [`UpdateObjectEncryption`] that is returned by [`MinioClient::update_object_encryption`](crate::s3::client::MinioClient::update_object_encryption).
///
/// This type alias simplifies the complex generic signature generated by the `typed_builder` crate.
pub type UpdateObjectEncryptionBldr = UpdateObjectEncryptionBuilder<(
    (MinioClient,),
    (),
    (),
    (),
    (BucketName,),
    (ObjectKey,),
    (String,),
    (),
    (),
)>;

impl S3Api for UpdateObjectEncryption {
    type S3Response = UpdateObjectEncryptionResponse;
}

const ENCRYPTION_XMLNS: &str = "http://s3.amazonaws.com/doc/2006-03-01/";

fn object_encryption_xml(kms_key_arn: &str, bucket_key_enabled: Option<bool>) -> Bytes {
    let mut data = String::from("<ObjectEncryption xmlns=\"");
    data.push_str(ENCRYPTION_XMLNS);
    data.push_str("\"><SSE-KMS>");
    if let Some(enabled) = bucket_key_enabled {
        data.push_str("<BucketKeyEnabled>");
        data.push_str(if enabled { "true" } else { "false" });
        data.push_str("</BucketKeyEnabled>");
    }
    data.push_str("<KMSKeyArn>");
    data.push_str(kms_key_arn);
    data.push_str("</KMSKeyArn></SSE-KMS></ObjectEncryption>");
    Bytes::from(data)
}

impl ToS3Request for UpdateObjectEncryption {
    fn to_s3request(self) -> Result<S3Request, ValidationErr> {
        if self.kms_key_arn.trim().is_empty() {
            return Err(ValidationErr::StrError {
                message: "KMSKeyArn is required for UpdateObjectEncryption".into(),
                source: None,
            });
        }

        let bytes: Bytes = object_encryption_xml(&self.kms_key_arn, self.bucket_key_enabled);

        let mut headers: Multimap = self.extra_headers.unwrap_or_default();
        headers.add(CONTENT_MD5, md5sum_hash(bytes.as_ref()));

        let mut query_params: Multimap = insert(self.extra_query_params, "encryption");
        query_params.add_version(self.version_id);

        let body = Arc::new(SegmentedBytes::from(bytes));

        Ok(S3Request::builder()
            .client(self.client)
            .method(Method::PUT)
            .region(self.region)
            .bucket(self.bucket)
            .object(self.object)
            .query_params(query_params)
            .headers(headers)
            .body(body)
            .build())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::s3::creds::StaticProvider;
    use crate::s3::http::BaseUrl;

    fn dummy_client() -> MinioClient {
        let base_url: BaseUrl = "http://localhost:9000".parse().unwrap();
        let provider = StaticProvider::new("minioadmin", "minioadmin", None);
        MinioClient::new(base_url, Some(provider), None, None).unwrap()
    }

    #[test]
    fn xml_body_includes_bucket_key_enabled_when_set() {
        let xml = object_encryption_xml("arn:aws:kms:key", Some(true));
        let xml = String::from_utf8(xml.to_vec()).unwrap();
        assert_eq!(
            xml,
            "<ObjectEncryption xmlns=\"http://s3.amazonaws.com/doc/2006-03-01/\">\
             <SSE-KMS><BucketKeyEnabled>true</BucketKeyEnabled>\
             <KMSKeyArn>arn:aws:kms:key</KMSKeyArn></SSE-KMS></ObjectEncryption>"
        );
    }

    #[test]
    fn xml_body_omits_bucket_key_enabled_when_none() {
        let xml = object_encryption_xml("my-key", None);
        let xml = String::from_utf8(xml.to_vec()).unwrap();
        assert_eq!(
            xml,
            "<ObjectEncryption xmlns=\"http://s3.amazonaws.com/doc/2006-03-01/\">\
             <SSE-KMS><KMSKeyArn>my-key</KMSKeyArn></SSE-KMS></ObjectEncryption>"
        );
        assert!(!xml.contains("BucketKeyEnabled"));
    }

    #[test]
    fn xml_body_emits_false_bucket_key_enabled() {
        let xml = object_encryption_xml("my-key", Some(false));
        let xml = String::from_utf8(xml.to_vec()).unwrap();
        assert!(xml.contains("<BucketKeyEnabled>false</BucketKeyEnabled>"));
    }

    #[test]
    fn request_sets_encryption_query_and_put_method() {
        let req = UpdateObjectEncryption::builder()
            .client(dummy_client())
            .bucket(BucketName::new("mybucket").unwrap())
            .object(ObjectKey::new("myobject").unwrap())
            .kms_key_arn("my-key")
            .build()
            .to_s3request()
            .unwrap();

        assert_eq!(
            req.query_params.get("encryption").map(String::as_str),
            Some("")
        );
        assert!(req.query_params.get("versionId").is_none());
    }

    #[test]
    fn request_includes_version_id_when_set() {
        let req = UpdateObjectEncryption::builder()
            .client(dummy_client())
            .bucket(BucketName::new("mybucket").unwrap())
            .object(ObjectKey::new("myobject").unwrap())
            .kms_key_arn("my-key")
            .version_id(VersionId::new("test-version-id").unwrap())
            .build()
            .to_s3request()
            .unwrap();

        assert!(req.query_params.get("encryption").is_some());
        assert_eq!(
            req.query_params.get("versionId").map(String::as_str),
            Some("test-version-id")
        );
    }

    #[test]
    fn request_rejects_empty_kms_key_arn() {
        let result = UpdateObjectEncryption::builder()
            .client(dummy_client())
            .bucket(BucketName::new("mybucket").unwrap())
            .object(ObjectKey::new("myobject").unwrap())
            .kms_key_arn("")
            .build()
            .to_s3request();

        assert!(result.is_err());
    }
}
