[package]
name = "minio-macros"
version = "0.1.0"
edition = "2024"

[dependencies]
uuid = { workspace = true, features = ["v4"] }
futures-util = { workspace = true }

syn = { workspace = true, features = ["full"] }
proc-macro2 = { workspace = true }
quote = { workspace = true }
darling = { workspace = true }
darling_core = { workspace = true }

[dev-dependencies]
minio-common = { path = "../common" }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true
