  name: Label Checker
  on:
    pull_request:
      types:
        - opened
        - synchronize
        - labeled
        - unlabeled
  jobs:
    check_labels:
      name: Check for labels
      runs-on: ubuntu-latest
      steps:
        - uses: docker://agilepathway/pull-request-label-checker:latest
          with:
            any_of: highlight,breaking-change,security-fix,enhancement,bug,cleanup-rewrite,regression-fix,codex
            repo_token: ${{ secrets.GITHUB_TOKEN }}
