name: MinIO Rust Library

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        cargo fmt --all -- --check
        cargo clippy --all-targets --all-features
        cargo build --bins --examples --tests --benches --verbose

    - name: Run tests S3
      run: |
        ./tests/start-server.sh s3
        export SERVER_ENDPOINT=localhost:9000
        export ACCESS_KEY=minioadmin
        export SECRET_KEY=minioadmin
        export ENABLE_HTTPS=1
        export SSL_CERT_FILE=./tests/public.crt
        cargo test --verbose -- --nocapture :s3: 

    - name: Run tests S3Express
      run: |
        ./tests/start-server.sh s3express
        export SERVER_ENDPOINT=localhost:9000
        export ACCESS_KEY=minioadmin
        export SECRET_KEY=minioadmin
        export ENABLE_HTTPS=1
        export SSL_CERT_FILE=./tests/public.crt
        cargo test --verbose -- --nocapture :s3express: 
