name: MinIO Rust Library

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        cargo fmt --all -- --check
        cargo clippy --all-targets --all-features -- -A clippy::result_large_err -A clippy::type_complexity -A clippy::too_many_arguments
        cargo build --verbose

    - name: Run tests
      run: |
        ./tests/start-server.sh
        export SERVER_ENDPOINT=localhost:9000
        export ACCESS_KEY=minioadmin
        export SECRET_KEY=minioadmin
        export ENABLE_HTTPS=1
        export SSL_CERT_FILE=./tests/public.crt
        cargo test --verbose -- --nocapture
