name: MinIO Rust Library

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        cargo fmt --all -- --check
        cargo clippy --all-targets --all-features -- -A clippy::result_large_err -A clippy::type_complexity -A clippy::too_many_arguments
        cargo build --bins --examples --tests --benches --verbose

    - name: Run tests
      run: |
        truncate --size=6M asiaphotos-2015.zip
        ./tests/start-server.sh
        export SERVER_ENDPOINT=localhost:9000
        export ACCESS_KEY=minioadmin
        export SECRET_KEY=minioadmin
        export ENABLE_HTTPS=1
        export SSL_CERT_FILE=./tests/public.crt
        cargo test --verbose -- --nocapture
